# Generated by Django 4.0.6 on 2022-07-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('designation', models.CharField(choices=[('G', 'Good Day'), ('O', 'OK Day'), ('B', 'Bad Day')], default='G', max_length=1)),
            ],
        ),
    ]
