# Generated by Django 4.0.6 on 2022-07-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('Ne', 'Neutral')], default='P', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='feelings',
            field=models.ManyToManyField(to='main_app.feeling'),
        ),
    ]
