# Generated by Django 4.0.6 on 2022-07-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeling_mood_user_mood_feelings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='designation',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Positive', max_length=15),
        ),
    ]
