# Generated by Django 4.0.6 on 2022-07-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeling_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='designation',
            field=models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('Ne', 'Neutral')], default='P', max_length=2),
        ),
    ]
